version: "3.8"  # optional since v1.27.0
services:
  service1:
    build: .
    image: serviceone
    expose:
      - 3000 # host:container
    deploy:
      mode: replicated
      replicas: 3
  service2:
    build: .
    image: servicetwo
    expose:
      - 3001 # host:container
    deploy:
      mode: replicated
      replicas: 2
  